name: service-ci-on-pull-request
on:
  pull_request:
    branches:
      - services/**

permissions:
  contents: read
  pull-requests: write

jobs:
  params:
    uses: ./.github/workflows/params-on-call.yaml

  ci:
    needs: params
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imágenes de servicio y pruebas
        env:
          DIRECTORY: ${{ needs.params.outputs.directory }}
        run: |
          # contruir ambas imágenes para validar proceso
          docker build --target service -t service ${{ env.DIRECTORY }}
          docker build --target testing -t testing ${{ env.DIRECTORY }}

      - name: 'Comentario de PR: Ejecutando pruebas'
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ⚙ Ejecutando pruebas unitarias...

      - name: Ejecutar imagen de contenedor de pruebas
        run: docker run --rm testing

      - name: 'Comentario de PR: Pruebas exitosas'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ✅ Pruebas unitarias exitosas
